//------------------------------------------------------------------------------
// <auto-generated>
//     Manually maintained - do not run ResXFileCodeGenerator on strings.resx
// </auto-generated>
//------------------------------------------------------------------------------

namespace GilledWars {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {

        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new global::System.Resources.ResourceManager("GilledWars.strings", typeof(strings).Assembly);
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static string StartLoggingBtnText {
            get { return ResourceManager.GetString("StartLoggingBtnText", resourceCulture); }
        }

        internal static string StopLoggingBtnText {
            get { return ResourceManager.GetString("StopLoggingBtnText", resourceCulture); }
        }

        internal static string MeasureFishBtnText {
            get { return ResourceManager.GetString("MeasureFishBtnText", resourceCulture); }
        }

        internal static string CompactModeBtnText {
            get { return ResourceManager.GetString("CompactModeBtnText", resourceCulture); }
        }

        internal static string WhatsBitingBtnText {
            get { return ResourceManager.GetString("WhatsBitingBtnText", resourceCulture); }
        }

        internal static string ProfitTrackerBtnText {
            get { return ResourceManager.GetString("ProfitTrackerBtnText", resourceCulture); }
        }

        internal static string RecentCatchesText {
            get { return ResourceManager.GetString("RecentCatchesText", resourceCulture); }
        }

        internal static string HostTournamentBtnText {
            get { return ResourceManager.GetString("HostTournamentBtnText", resourceCulture); }
        }

        internal static string JoinTournamentBtnText {
            get { return ResourceManager.GetString("JoinTournamentBtnText", resourceCulture); }
        }

        internal static string UseDrfCheckboxText {
            get { return ResourceManager.GetString("UseDrfCheckboxText", resourceCulture); }
        }

        internal static string UseDrfTooltip {
            get { return ResourceManager.GetString("UseDrfTooltip", resourceCulture); }
        }

        internal static string WhatsBitingTooltip {
            get { return ResourceManager.GetString("WhatsBitingTooltip", resourceCulture); }
        }

        internal static string ProfitTrackerTooltip {
            get { return ResourceManager.GetString("ProfitTrackerTooltip", resourceCulture); }
        }

        internal static string CloseLodgeTooltip {
            get { return ResourceManager.GetString("CloseLodgeTooltip", resourceCulture); }
        }

        internal static string SearchFishPlaceholder {
            get { return ResourceManager.GetString("SearchFishPlaceholder", resourceCulture); }
        }

        internal static string CollapseBtnText {
            get { return ResourceManager.GetString("CollapseBtnText", resourceCulture); }
        }

        internal static string RevealBtnText {
            get { return ResourceManager.GetString("RevealBtnText", resourceCulture); }
        }

        internal static string ResetFiltersBtnText {
            get { return ResourceManager.GetString("ResetFiltersBtnText", resourceCulture); }
        }

        internal static string PushPbBtnText {
            get { return ResourceManager.GetString("PushPbBtnText", resourceCulture); }
        }

        internal static string ZoneAnalyzerBtnText {
            get { return ResourceManager.GetString("ZoneAnalyzerBtnText", resourceCulture); }
        }

        internal static string MetaProgressBtnText {
            get { return ResourceManager.GetString("MetaProgressBtnText", resourceCulture); }
        }

        internal static string PushPbTooltip {
            get { return ResourceManager.GetString("PushPbTooltip", resourceCulture); }
        }

        internal static string ZoneAnalyzerTooltip {
            get { return ResourceManager.GetString("ZoneAnalyzerTooltip", resourceCulture); }
        }

        internal static string MetaProgressTooltip {
            get { return ResourceManager.GetString("MetaProgressTooltip", resourceCulture); }
        }

        internal static string HostSetupTitle {
            get { return ResourceManager.GetString("HostSetupTitle", resourceCulture); }
        }

        internal static string StartDelayLabel {
            get { return ResourceManager.GetString("StartDelayLabel", resourceCulture); }
        }

        internal static string DurationLabel {
            get { return ResourceManager.GetString("DurationLabel", resourceCulture); }
        }

        internal static string TrackingModeLabel {
            get { return ResourceManager.GetString("TrackingModeLabel", resourceCulture); }
        }

        internal static string TargetSpeciesLabel {
            get { return ResourceManager.GetString("TargetSpeciesLabel", resourceCulture); }
        }

        internal static string WinFactorLabel {
            get { return ResourceManager.GetString("WinFactorLabel", resourceCulture); }
        }

        internal static string CreateRoomBtn {
            get { return ResourceManager.GetString("CreateRoomBtn", resourceCulture); }
        }

        internal static string JoinRoomTitle {
            get { return ResourceManager.GetString("JoinRoomTitle", resourceCulture); }
        }

        internal static string EnterRoomCodeLabel {
            get { return ResourceManager.GetString("EnterRoomCodeLabel", resourceCulture); }
        }

        internal static string JoinRoomBtn {
            get { return ResourceManager.GetString("JoinRoomBtn", resourceCulture); }
        }

        internal static string ManualVerifyTitle {
            get { return ResourceManager.GetString("ManualVerifyTitle", resourceCulture); }
        }

        internal static string PasteCodePlaceholder {
            get { return ResourceManager.GetString("PasteCodePlaceholder", resourceCulture); }
        }

        internal static string VerifyCodeBtn {
            get { return ResourceManager.GetString("VerifyCodeBtn", resourceCulture); }
        }

        internal static string TrackingModesInfo {
            get { return ResourceManager.GetString("TrackingModesInfo", resourceCulture); }
        }

        internal static string LeaderboardTitle {
            get { return ResourceManager.GetString("LeaderboardTitle", resourceCulture); }
        }

        internal static string SortLabel {
            get { return ResourceManager.GetString("SortLabel", resourceCulture); }
        }

        internal static string FishLabel {
            get { return ResourceManager.GetString("FishLabel", resourceCulture); }
        }

        internal static string AllSpeciesFilterBtn {
            get { return ResourceManager.GetString("AllSpeciesFilterBtn", resourceCulture); }
        }

        internal static string RefreshBtn {
            get { return ResourceManager.GetString("RefreshBtn", resourceCulture); }
        }

        internal static string WeightDropdown {
            get { return ResourceManager.GetString("WeightDropdown", resourceCulture); }
        }

        internal static string LengthDropdown {
            get { return ResourceManager.GetString("LengthDropdown", resourceCulture); }
        }

        internal static string BitingNowTitle {
            get { return ResourceManager.GetString("BitingNowTitle", resourceCulture); }
        }

        internal static string PbWeightLabel {
            get { return ResourceManager.GetString("PbWeightLabel", resourceCulture); }
        }

        internal static string PbLengthLabel {
            get { return ResourceManager.GetString("PbLengthLabel", resourceCulture); }
        }

        internal static string BaitLabel {
            get { return ResourceManager.GetString("BaitLabel", resourceCulture); }
        }

        internal static string ExpandingMainView {
            get { return ResourceManager.GetString("ExpandingMainView", resourceCulture); }
        }

        internal static string LeaderboardRefreshed {
            get { return ResourceManager.GetString("LeaderboardRefreshed", resourceCulture); }
        }

        internal static string NoRecordsFound {
            get { return ResourceManager.GetString("NoRecordsFound", resourceCulture); }
        }

        internal static string NetworkError {
            get { return ResourceManager.GetString("NetworkError", resourceCulture); }
        }

        internal static string NoAchievFound {
            get { return ResourceManager.GetString("NoAchievFound", resourceCulture); }
        }

        internal static string TourneyBegin {
            get { return ResourceManager.GetString("TourneyBegin", resourceCulture); }
        }

        internal static string ResultsSubmitted {
            get { return ResourceManager.GetString("ResultsSubmitted", resourceCulture); }
        }

        internal static string LoadingTop10 {
            get { return ResourceManager.GetString("LoadingTop10", resourceCulture); }
        }

        internal static string Ready {
            get { return ResourceManager.GetString("Ready", resourceCulture); }
        }

        internal static string Measuring {
            get { return ResourceManager.GetString("Measuring", resourceCulture); }
        }

        internal static string DrfActive {
            get { return ResourceManager.GetString("DrfActive", resourceCulture); }
        }

        internal static string DrfPaused {
            get { return ResourceManager.GetString("DrfPaused", resourceCulture); }
        }

        internal static string ApiPaused {
            get { return ResourceManager.GetString("ApiPaused", resourceCulture); }
        }

        internal static string StartingIn {
            get { return ResourceManager.GetString("StartingIn", resourceCulture); }
        }

        internal static string Top5Catches {
            get { return ResourceManager.GetString("Top5Catches", resourceCulture); }
        }

        internal static string ApiErrorBags {
            get { return ResourceManager.GetString("ApiErrorBags", resourceCulture); }
        }

        internal static string FishMeasuredCount {
            get { return ResourceManager.GetString("FishMeasuredCount", resourceCulture); }
        }

        internal static string ApiErrorKey {
            get { return ResourceManager.GetString("ApiErrorKey", resourceCulture); }
        }

        internal static string SnapshotSaved {
            get { return ResourceManager.GetString("SnapshotSaved", resourceCulture); }
        }

        internal static string DrfErrorToken {
            get { return ResourceManager.GetString("DrfErrorToken", resourceCulture); }
        }

        internal static string DrfConnected {
            get { return ResourceManager.GetString("DrfConnected", resourceCulture); }
        }

        internal static string DrfFailed {
            get { return ResourceManager.GetString("DrfFailed", resourceCulture); }
        }

        internal static string CasualLoggingStopped {
            get { return ResourceManager.GetString("CasualLoggingStopped", resourceCulture); }
        }

        internal static string RoomCreated {
            get { return ResourceManager.GetString("RoomCreated", resourceCulture); }
        }

        internal static string ApiErrorRoom {
            get { return ResourceManager.GetString("ApiErrorRoom", resourceCulture); }
        }

        internal static string InvalidRoomCode {
            get { return ResourceManager.GetString("InvalidRoomCode", resourceCulture); }
        }

        internal static string RoomNotFound {
            get { return ResourceManager.GetString("RoomNotFound", resourceCulture); }
        }

        internal static string DrfResumeWait {
            get { return ResourceManager.GetString("DrfResumeWait", resourceCulture); }
        }

        internal static string TourneyStarted {
            get { return ResourceManager.GetString("TourneyStarted", resourceCulture); }
        }

        internal static string BackupCopied {
            get { return ResourceManager.GetString("BackupCopied", resourceCulture); }
        }

        internal static string TourneyCatchAlert {
            get { return ResourceManager.GetString("TourneyCatchAlert", resourceCulture); }
        }

        internal static string CaughtAlert {
            get { return ResourceManager.GetString("CaughtAlert", resourceCulture); }
        }

        internal static string FishCodeCopied {
            get { return ResourceManager.GetString("FishCodeCopied", resourceCulture); }
        }

        internal static string RefreshCooldown {
            get { return ResourceManager.GetString("RefreshCooldown", resourceCulture); }
        }

        internal static string SubmitCooldown {
            get { return ResourceManager.GetString("SubmitCooldown", resourceCulture); }
        }

        internal static string UiToggled {
            get { return ResourceManager.GetString("UiToggled", resourceCulture); }
        }

        internal static string PbClipText {
            get { return ResourceManager.GetString("PbClipText", resourceCulture); }
        }

        internal static string AutoSyncSuccess {
            get { return ResourceManager.GetString("AutoSyncSuccess", resourceCulture); }
        }

        internal static string NoNewSubmissions {
            get { return ResourceManager.GetString("NoNewSubmissions", resourceCulture); }
        }

        internal static string PushingPBs {
            get { return ResourceManager.GetString("PushingPBs", resourceCulture); }
        }

        internal static string ServerRejected {
            get { return ResourceManager.GetString("ServerRejected", resourceCulture); }
        }

        internal static string FailedConnectLB {
            get { return ResourceManager.GetString("FailedConnectLB", resourceCulture); }
        }

        internal static string TournamentOver {
            get { return ResourceManager.GetString("TournamentOver", resourceCulture); }
        }

        internal static string JunkMessages {
            get { return ResourceManager.GetString("JunkMessages", resourceCulture); }
        }

        internal static string TreasureMessages {
            get { return ResourceManager.GetString("TreasureMessages", resourceCulture); }
        }

        internal static string Loading {
            get { return ResourceManager.GetString("Loading", resourceCulture); }
        }

        internal static string MissingLabel {
            get { return ResourceManager.GetString("MissingLabel", resourceCulture); }
        }

        internal static string AllLabel {
            get { return ResourceManager.GetString("AllLabel", resourceCulture); }
        }

        internal static string BitingNowLoading {
            get { return ResourceManager.GetString("BitingNowLoading", resourceCulture); }
        }

        internal static string ToggleBitingTooltip {
            get { return ResourceManager.GetString("ToggleBitingTooltip", resourceCulture); }
        }

        internal static string TargetAllSpecies {
            get { return ResourceManager.GetString("TargetAllSpecies", resourceCulture); }
        }

        internal static string TargetPrefix {
            get { return ResourceManager.GetString("TargetPrefix", resourceCulture); }
        }

        internal static string ApiErrorKeyOrChar {
            get { return ResourceManager.GetString("ApiErrorKeyOrChar", resourceCulture); }
        }

        internal static string LoadingData {
            get { return ResourceManager.GetString("LoadingData", resourceCulture); }
        }

        internal static string FetchingAchievements {
            get { return ResourceManager.GetString("FetchingAchievements", resourceCulture); }
        }

        internal static string SearchSpeciesPlaceholder {
            get { return ResourceManager.GetString("SearchSpeciesPlaceholder", resourceCulture); }
        }

        internal static string Scanning {
            get { return ResourceManager.GetString("Scanning", resourceCulture); }
        }

        internal static string Creating {
            get { return ResourceManager.GetString("Creating", resourceCulture); }
        }

        internal static string Joining {
            get { return ResourceManager.GetString("Joining", resourceCulture); }
        }

        internal static string TourneyEndedTitle {
            get { return ResourceManager.GetString("TourneyEndedTitle", resourceCulture); }
        }

        internal static string TourneyEndedManualTitle {
            get { return ResourceManager.GetString("TourneyEndedManualTitle", resourceCulture); }
        }

        internal static string TourneySubmitting {
            get { return ResourceManager.GetString("TourneySubmitting", resourceCulture); }
        }

        internal static string TourneyResultsInitial {
            get { return ResourceManager.GetString("TourneyResultsInitial", resourceCulture); }
        }

        internal static string TourneyPostedDiscord {
            get { return ResourceManager.GetString("TourneyPostedDiscord", resourceCulture); }
        }

        internal static string TourneyApiFailed {
            get { return ResourceManager.GetString("TourneyApiFailed", resourceCulture); }
        }

        internal static string TourneyNetworkError {
            get { return ResourceManager.GetString("TourneyNetworkError", resourceCulture); }
        }

        internal static string TourneyComplete {
            get { return ResourceManager.GetString("TourneyComplete", resourceCulture); }
        }

        internal static string CornerIconTooltip {
            get { return ResourceManager.GetString("CornerIconTooltip", resourceCulture); }
        }

        internal static string CornerIconSubtitle {
            get { return ResourceManager.GetString("CornerIconSubtitle", resourceCulture); }
        }

        internal static string ProfitTotalDefault {
            get { return ResourceManager.GetString("ProfitTotalDefault", resourceCulture); }
        }

        internal static string GphDefault {
            get { return ResourceManager.GetString("GphDefault", resourceCulture); }
        }

        internal static string ServerError {
            get { return ResourceManager.GetString("ServerError", resourceCulture); }
        }

        internal static string NoCatchesYet {
            get { return ResourceManager.GetString("NoCatchesYet", resourceCulture); }
        }

        internal static string RankLabel {
            get { return ResourceManager.GetString("RankLabel", resourceCulture); }
        }

        internal static string AnglerLabel {
            get { return ResourceManager.GetString("AnglerLabel", resourceCulture); }
        }

        internal static string SpeciesLabel {
            get { return ResourceManager.GetString("SpeciesLabel", resourceCulture); }
        }

        internal static string MetaTrackerTitle {
            get { return ResourceManager.GetString("MetaTrackerTitle", resourceCulture); }
        }

        internal static string CasualFishingLabel {
            get { return ResourceManager.GetString("CasualFishingLabel", resourceCulture); }
        }

        internal static string CasualFishingTooltip {
            get { return ResourceManager.GetString("CasualFishingTooltip", resourceCulture); }
        }

        internal static string TourneyModeTooltip {
            get { return ResourceManager.GetString("TourneyModeTooltip", resourceCulture); }
        }

        internal static string FishLogTooltip {
            get { return ResourceManager.GetString("FishLogTooltip", resourceCulture); }
        }

        internal static string LeaderboardTooltip {
            get { return ResourceManager.GetString("LeaderboardTooltip", resourceCulture); }
        }

        internal static string OpenWebsiteTooltip {
            get { return ResourceManager.GetString("OpenWebsiteTooltip", resourceCulture); }
        }

        internal static string NoneLogged {
            get { return ResourceManager.GetString("NoneLogged", resourceCulture); }
        }

        internal static string CheaterDetected {
            get { return ResourceManager.GetString("CheaterDetected", resourceCulture); }
        }

        internal static string CloseBtnText {
            get { return ResourceManager.GetString("CloseBtnText", resourceCulture); }
        }

        internal static string UploadingText {
            get { return ResourceManager.GetString("UploadingText", resourceCulture); }
        }

        internal static string EndSubmitBtn {
            get { return ResourceManager.GetString("EndSubmitBtn", resourceCulture); }
        }

        internal static string ReCopyCodeBtn {
            get { return ResourceManager.GetString("ReCopyCodeBtn", resourceCulture); }
        }

        internal static string ReCopyCodeTooltip {
            get { return ResourceManager.GetString("ReCopyCodeTooltip", resourceCulture); }
        }

        internal static string ExitTourneyBtn {
            get { return ResourceManager.GetString("ExitTourneyBtn", resourceCulture); }
        }

        internal static string ExitTourneyTooltip {
            get { return ResourceManager.GetString("ExitTourneyTooltip", resourceCulture); }
        }

        internal static string Top5CatchesLabel {
            get { return ResourceManager.GetString("Top5CatchesLabel", resourceCulture); }
        }

        internal static string ExitedTournament {
            get { return ResourceManager.GetString("ExitedTournament", resourceCulture); }
        }

        internal static string TournamentOverWeighing {
            get { return ResourceManager.GetString("TournamentOverWeighing", resourceCulture); }
        }

        internal static string RecentCatchesCompact {
            get { return ResourceManager.GetString("RecentCatchesCompact", resourceCulture); }
        }

        internal static string MaximizeUI {
            get { return ResourceManager.GetString("MaximizeUI", resourceCulture); }
        }

        internal static string NoFishingZone {
            get { return ResourceManager.GetString("NoFishingZone", resourceCulture); }
        }

        internal static string BitingApiSyncing {
            get { return ResourceManager.GetString("BitingApiSyncing", resourceCulture); }
        }

        internal static string NameColumnHeader {
            get { return ResourceManager.GetString("NameColumnHeader", resourceCulture); }
        }

        internal static string BaitColumnHeader {
            get { return ResourceManager.GetString("BaitColumnHeader", resourceCulture); }
        }

        internal static string TimeColumnHeader {
            get { return ResourceManager.GetString("TimeColumnHeader", resourceCulture); }
        }

        internal static string HoleColumnHeader {
            get { return ResourceManager.GetString("HoleColumnHeader", resourceCulture); }
        }

        internal static string ToggleGridView {
            get { return ResourceManager.GetString("ToggleGridView", resourceCulture); }
        }

        internal static string SettingToggleUI {
            get { return ResourceManager.GetString("SettingToggleUI", resourceCulture); }
        }

        internal static string SettingToggleUIDesc {
            get { return ResourceManager.GetString("SettingToggleUIDesc", resourceCulture); }
        }

        internal static string SettingCustomApiKey {
            get { return ResourceManager.GetString("SettingCustomApiKey", resourceCulture); }
        }

        internal static string SettingCustomApiKeyDesc {
            get { return ResourceManager.GetString("SettingCustomApiKeyDesc", resourceCulture); }
        }

        internal static string SettingDrfToken {
            get { return ResourceManager.GetString("SettingDrfToken", resourceCulture); }
        }

        internal static string SettingDrfTokenDesc {
            get { return ResourceManager.GetString("SettingDrfTokenDesc", resourceCulture); }
        }

        internal static string SettingDiscordWebhook {
            get { return ResourceManager.GetString("SettingDiscordWebhook", resourceCulture); }
        }

        internal static string SettingDiscordWebhookDesc {
            get { return ResourceManager.GetString("SettingDiscordWebhookDesc", resourceCulture); }
        }

        internal static string SettingCornerIcon {
            get { return ResourceManager.GetString("SettingCornerIcon", resourceCulture); }
        }

        internal static string SettingCornerIconDesc {
            get { return ResourceManager.GetString("SettingCornerIconDesc", resourceCulture); }
        }

        internal static string SettingAutoStartLogging {
            get { return ResourceManager.GetString("SettingAutoStartLogging", resourceCulture); }
        }

        internal static string SettingAutoStartLoggingDesc {
            get { return ResourceManager.GetString("SettingAutoStartLoggingDesc", resourceCulture); }
        }

        internal static string SettingAutoOpenBiting {
            get { return ResourceManager.GetString("SettingAutoOpenBiting", resourceCulture); }
        }

        internal static string SettingAutoOpenBitingDesc {
            get { return ResourceManager.GetString("SettingAutoOpenBitingDesc", resourceCulture); }
        }

        internal static string SettingShowProfit {
            get { return ResourceManager.GetString("SettingShowProfit", resourceCulture); }
        }

        internal static string SettingShowProfitDesc {
            get { return ResourceManager.GetString("SettingShowProfitDesc", resourceCulture); }
        }

        internal static string SettingShowTimeOfDay {
            get { return ResourceManager.GetString("SettingShowTimeOfDay", resourceCulture); }
        }

        internal static string SettingShowTimeOfDayDesc {
            get { return ResourceManager.GetString("SettingShowTimeOfDayDesc", resourceCulture); }
        }

        internal static string SettingLockTimeOfDay {
            get { return ResourceManager.GetString("SettingLockTimeOfDay", resourceCulture); }
        }

        internal static string SettingLockTimeOfDayDesc {
            get { return ResourceManager.GetString("SettingLockTimeOfDayDesc", resourceCulture); }
        }

        internal static string SettingWidgetIconSize {
            get { return ResourceManager.GetString("SettingWidgetIconSize", resourceCulture); }
        }

        internal static string SettingWidgetIconSizeDesc {
            get { return ResourceManager.GetString("SettingWidgetIconSizeDesc", resourceCulture); }
        }

        internal static string SettingTextLayout {
            get { return ResourceManager.GetString("SettingTextLayout", resourceCulture); }
        }

        internal static string SettingTextLayoutDesc {
            get { return ResourceManager.GetString("SettingTextLayoutDesc", resourceCulture); }
        }

        internal static string SettingUILanguage {
            get { return ResourceManager.GetString("SettingUILanguage", resourceCulture); }
        }

        internal static string SettingUILanguageDesc {
            get { return ResourceManager.GetString("SettingUILanguageDesc", resourceCulture); }
        }
    }
}
